apiVersion: v1
kind: Pod
metadata:
  name: nginx-using-process-capabilities-root-debug-emptydir
spec:
  containers:
  - name: webserver
    volumeMounts:
    - mountPath: /var/cache/nginx/
      name: nginx-vol
    - mountPath: /var/run/
      name: nginx-run
    imagePullPolicy: Always
    image: arindamgb/kubernetes-nginx-hardening:1.24.0-fcap-debug
    ports:
    - containerPort: 80
    securityContext:
      runAsUser: 20000
  volumes:
  - name: nginx-vol
    emptyDir: {}
  - name: nginx-run
    emptyDir: {}
