apiVersion: v1
kind: Pod
metadata:
  name: nginx-using-file-capabilities-non-root-debug
spec:
  securityContext:
    runAsUser: 1001
  containers:
  - name: webserver
    imagePullPolicy: Always
    image: arindamgb/kubernetes-nginx-hardening:1.24.0-fcap-debug
    ports:
    - containerPort: 80
